name: conda_cellbender
channels:
  - letaylor
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pandas
  - numpy
  - scipy
  - scanpy
  - python-igraph
  - plotnine
  - kneed
  - louvain
  - leidenalg
  - click
  - plotnine
  - matplotlib
  - pip
  - pip:
     - git+https://github.com/broadinstitute/CellBender.git
